apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: syndeses.syndesis.io
spec:
  group: syndesis.io
  names:
    kind: Syndesis
    listKind: SyndesisList
    plural: syndeses
    singular: syndesis
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            addons:
              description: Optional add on features that can be enabled.
              properties:
                camelk:
                  properties:
                    camelVersion:
                      type: string
                    camelkRuntime:
                      type: string
                    enabled:
                      type: boolean
                    image:
                      type: string
                  type: object
                dv:
                  properties:
                    enabled:
                      type: boolean
                    resources:
                      type: object
                  type: object
                jaeger:
                  properties:
                    enabled:
                      type: boolean
                    samplerParam:
                      type: string
                    samplerType:
                      type: string
                  type: object
                knative:
                  properties:
                    enabled:
                      type: boolean
                  type: object
                ops:
                  properties:
                    enabled:
                      type: boolean
                  type: object
                todo:
                  properties:
                    enabled:
                      type: boolean
                  type: object
              type: object
            components:
              description: Components is used to configure all the core components
                of Syndesis
              properties:
                database:
                  properties:
                    externalDbURL:
                      type: string
                    name:
                      type: string
                    resources:
                      properties:
                        volumeCapacity:
                          type: string
                      type: object
                    user:
                      type: string
                  type: object
                grafana:
                  properties:
                    resources:
                      type: object
                  type: object
                meta:
                  properties:
                    resources:
                      properties:
                        volumeCapacity:
                          type: string
                      type: object
                  type: object
                oauth:
                  properties:
                    sarNamespace:
                      type: string
                  type: object
                prometheus:
                  properties:
                    resources:
                      properties:
                        volumeCapacity:
                          type: string
                      type: object
                    rules:
                      type: string
                  type: object
                server:
                  properties:
                    features:
                      properties:
                        mavenRepositories:
                          additionalProperties:
                            type: string
                          type: object
                      type: object
                    resources:
                      type: object
                  type: object
                upgrade:
                  properties:
                    resources:
                      properties:
                        volumeCapacity:
                          type: string
                      type: object
                  type: object
              type: object
            imageStreamNamespace:
              type: string
          type: object
        status:
          properties:
            description:
              type: string
            forceUpgrade:
              type: boolean
            lastUpgradeFailure:
              format: date-time
              type: string
            phase:
              type: string
            reason:
              type: string
            targetVersion:
              type: string
            upgradeAttempts:
              format: int32
              type: integer
            version:
              type: string
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
