apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: syndeses.syndesis.io
spec:
  group: syndesis.io
  names:
    kind: Syndesis
    listKind: SyndesisList
    plural: syndeses
    singular: syndesis
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            addons:
              additionalProperties:
                items:
                  additionalProperties:
                    type: string
                  type: object
                type: array
              type: object
            components:
              properties:
                db:
                  properties:
                    database:
                      type: string
                    imageStreamNamespace:
                      type: string
                    resources:
                      properties:
                        limits:
                          additionalProperties:
                            type: string
                          description: 'Limits describes the maximum amount of compute
                            resources allowed. More info: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/'
                          type: object
                        requests:
                          additionalProperties:
                            type: string
                          description: 'Requests describes the minimum amount of compute
                            resources required. If Requests is omitted for a container,
                            it defaults to Limits if that is explicitly specified,
                            otherwise to an implementation-defined value. More info:
                            https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/'
                          type: object
                        volumeCapacity:
                          type: string
                      type: object
                    user:
                      type: string
                  type: object
                grafana:
                  properties:
                    resources:
                      properties:
                        limits:
                          additionalProperties:
                            type: string
                          description: 'Limits describes the maximum amount of compute
                            resources allowed. More info: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/'
                          type: object
                        requests:
                          additionalProperties:
                            type: string
                          description: 'Requests describes the minimum amount of compute
                            resources required. If Requests is omitted for a container,
                            it defaults to Limits if that is explicitly specified,
                            otherwise to an implementation-defined value. More info:
                            https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/'
                          type: object
                      type: object
                  type: object
                meta:
                  properties:
                    resources:
                      properties:
                        limits:
                          additionalProperties:
                            type: string
                          description: 'Limits describes the maximum amount of compute
                            resources allowed. More info: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/'
                          type: object
                        requests:
                          additionalProperties:
                            type: string
                          description: 'Requests describes the minimum amount of compute
                            resources required. If Requests is omitted for a container,
                            it defaults to Limits if that is explicitly specified,
                            otherwise to an implementation-defined value. More info:
                            https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/'
                          type: object
                        volumeCapacity:
                          type: string
                      type: object
                  type: object
                prometheus:
                  properties:
                    resources:
                      properties:
                        limits:
                          additionalProperties:
                            type: string
                          description: 'Limits describes the maximum amount of compute
                            resources allowed. More info: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/'
                          type: object
                        requests:
                          additionalProperties:
                            type: string
                          description: 'Requests describes the minimum amount of compute
                            resources required. If Requests is omitted for a container,
                            it defaults to Limits if that is explicitly specified,
                            otherwise to an implementation-defined value. More info:
                            https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/'
                          type: object
                        volumeCapacity:
                          type: string
                      type: object
                  type: object
                server:
                  properties:
                    features:
                      properties:
                        managementUrlFor3scale:
                          type: string
                          description: 'Allows to configure URL to 3scale in OpenShift.'
                      type: object
                    resources:
                      properties:
                        limits:
                          additionalProperties:
                            type: string
                          description: 'Limits describes the maximum amount of compute
                            resources allowed. More info: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/'
                          type: object
                        requests:
                          additionalProperties:
                            type: string
                          description: 'Requests describes the minimum amount of compute
                            resources required. If Requests is omitted for a container,
                            it defaults to Limits if that is explicitly specified,
                            otherwise to an implementation-defined value. More info:
                            https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/'
                          type: object
                      type: object
                  type: object
                upgrade:
                  properties:
                    resources:
                      properties:
                        volumeCapacity:
                          type: string
                      type: object
                  type: object
              type: object
            demoData:
              type: boolean
            deployIntegrations:
              type: boolean
            imageStreamNamespace:
              type: string
            integration:
              properties:
                limit:
                  format: int64
                  type: integer
                stateCheckInterval:
                  format: int64
                  type: integer
              type: object
            openShiftConsoleUrl:
              type: string
            registry:
              type: string
            routeHostname:
              type: string
            sarNamespace:
              type: string
            testSupport:
              type: boolean
          type: object
        status:
          properties:
            description:
              type: string
            forceUpgrade:
              type: boolean
            lastUpgradeFailure:
              format: date-time
              type: string
            phase:
              type: string
            reason:
              type: string
            targetVersion:
              type: string
            upgradeAttempts:
              format: int32
              type: integer
            version:
              type: string
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
