bases:
- ../app
images:
- name: docker.io/syndesis/syndesis-operator:latest
  newName: registry.redhat.io/fuse7/fuse-online-operator
  newTag: "1.8"
- name: centos/postgresql-10-centos7
  newName: registry.redhat.io/rhscl/postgresql-10-rhel7
  newTag: "1-59"
patchesJson6902:
- target:
    group: image.openshift.io
    version: v1
    kind: ImageStream
    name: syndesis-operator
  path: image-stream-patch.yaml
